### PR TITLE
Update to work with Sublime Text 3/Python 3

### PR DESCRIPTION
**Pull request by doublesharp**
* Support for apikey parameter
* Get values from settings file
* Show errors in quick menu
* Syntax highlighting

### CODE REVIEW

**Comment by patrickayoup** [comment]
Hi, sorry I missed the notification for this PR.. I'll try to look at this soon.

**Comment by patrickayoup** [comment]
Reference: #3

**Comment by doublesharp** [comment]
@patrickayoup - it just occurred to me that the apikey parameter might need to be conditional based on if it is present in the settings file or not. I needed it for some of the premium features but didn't test without it. 

`
self.apikey = settings.get('apikey')
`

**Comment by patrickayoup** [comment]
Reference: #2

**Pull request merged**
